name: scandit_flutter_datacapture_id
description: Scandit Data Capture SDK for Flutter.
version: 6.17.1
homepage: https://scandit.com



environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_core:
    '>=6.17.1 <6.17.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  linter: ^1.30.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.id
        pluginClass: ScanditFlutterDataCaptureIdProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureIdPlugin
