name: scandit_flutter_datacapture_id
description: This plugin implements the ID capture capabilities of the Scandit Data Capture SDK.
version: 6.20.2
homepage: https://scandit.com



environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_core:
    '>=6.20.2 <6.20.3'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  linter: ^1.30.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.id
        pluginClass: ScanditFlutterDataCaptureIdProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureId
