name: scandit_flutter_datacapture_id
description: This plugin implements the ID capture capabilities of the Scandit Data Capture SDK.
version: 7.6.1
homepage: https://scandit.com



environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_core:
    '>=7.6.1 <7.6.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.id
        pluginClass: ScanditFlutterDataCaptureIdProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureId
